---
title: "2023 List of Homework"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
## week 1
focal_paper <- list(
  title = "",
  topics = c("Focal paper & relevant references"),
  pdf = "",
  rmd = "",
  html = "homework/week_01/hw_01_references.html",
  due_date = "16 Jan",
  percent = "5%"
)

## week 2
message_box <- list(
  title = "",
  topics = c("Papers"),
  pdf = "",
  rmd = "",
  html = "homework/week_02/hw_02_papers.html",
  due_date = "23 Jan",
  percent = "5%"
)

## week 3
holiday_1 <- list(
  title = "",
  topics = c("Message Box"),
  pdf = "",
  rmd = "",
  html = "homework/week_03/hw_02_message_box.html",
  due_date = "30 Jan",
  percent = "5%"
)

## week 4
proposal_draft <- list(
  title = "",
  topics = c("Draft proposal introduction"),
  pdf = "",
  rmd = "",
  html = "homework/week_04/hw_03_proposal_intro.html",
  due_date = "6 Feb",
  percent = "15%"
)

## week 5
cover_letter <- list(
  title = "",
  topics = c("Cover letter to journal"),
  pdf = "",
  rmd = "",
  html = "homework/week_05/hw_04_cover_letter.html",
  due_date = "13 Feb",
  percent = "10%"
)

## week 6
review_draft <- list(
  title = "",
  topics = c("Peer review of paper"),
  pdf = "",
  rmd = "",
  html = "homework/week_06/hw_05_peer_review.html",
  due_date = "20 Feb",
  percent = "15%"
)

## week 7
scicomm <- list(
  title = "",
  topics = c("Tweet thread or blog post"),
  pdf = "",
  rmd = "",
  html = "homework/week_07/hw_06_scicomm.html",
  due_date = "Mar 6",
  percent = "10%"
)

## week 8
holiday_2 <- list(
  title = "",
  topics = c("<i>No Homework</i>"),
  pdf = "",
  rmd = "",
 # html = "",
  due_date = "",
  percent = ""
)

## week 9
presentation <- list(
  title = "",
  topics = c("Proposal presentation"),
  pdf = "",
  rmd = "",
  html = "homework/week_09/hw_07_presentations.html",
  due_date = "Mar 6<br>(In class)",
  percent = "15%"
)

## week 10
proposal_final <- list(
  title = "",
  topics = c("Final proposal"),
  pdf = "",
  rmd = "",
  html = "homework/week_10/hw_08_proposal.html",
  due_date = "16 Mar",
  percent = "20%"
)
```

