---
title: "Scientific outreach"
subtitle: "Homework #6"
author: "FISH 521 - Proposal Writing and Professional Development"
date: "27 February 2023"
output:
  html_document:
    theme: darkly
    highlight: textmate
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

## Instructions

You have two options for your homework this week. Both of them will require you to use some of the concepts you learned in class this week.

### Option 1

Write a "Twitter thread" consisting of 6 or more separate tweets that tells the story about a paper of interest (eg, the paper you chose for assignment #1). Your thread should include a combination of *text of your own writing* and images copied/pasted from the paper itself (eg, [here](https://twitter.com/mark_scheuerell/status/1328405485901336576) and [here](https://twitter.com/sr320/status/1629158452588331010)). For your images, be sure to include some alternate text that could be used by someone who is visually impaired to understand the image content. A few things to note

-   Any one tweet is limitied to 280 characters, including spaces.

-   The first tweet should introduce the paper and include a link to its online version.

-   The last tweet should include the take-home message(s).

### Option 2

Write a blog post about a paper, or anything scientific that you find fascinating, bothersome, etc, using the [blog platform covered in class](https://sr320.github.io/course-fish521-2023/lectures/week_07/lec_06b_websites.html). The topic could be something you study or work on, or something that you're just interested in more generally. Your post should be approximately 1000 words. Your intention should be to convey the novelty or importance of the topic *using plain writing*. If you're looking for inspiration, consider some examples from [*Small Pond Science*](https://smallpondscience.com/) or [*Dynamic Ecology*](https://dynamicecology.wordpress.com/). Also have a look at post I made on a blog developed using the Quarto blog format - [**Genetics: Does it really matter?**](https://sr320.github.io/tumbling-oysters/posts/cool-paper/)

## Submission

In both cases you will simply have a url to share. Please place a markdown file with the url in your homework directory.
